#!/usr/bin/env bash

if [[ ! $(type -t xclip) = file ]]; then
	echo "make sure you install xclip"
	exit 1
fi

blogDirName=$(basename "$PWD")
blogName=$(echo $blogDirName | cut -d "-" -f 2- | tr '-' " ")
blogSlugName=$(echo $blogDirName | cut -d "-" -f 2- | tr '[:upper:]' '[:lower:]')
blogDate=$(date '+%Y-%m-%d')

# use double quotes to have variable expansion and escape internal double quotes
fm="+++
title = \"$blogName\"
slug = \"$blogSlugName\"
date = $blogDate
draft = true
[extra]
toc = false
side_toc = false
og_image = \"blog/$blogDirName/preview.png\"
+++
"

# quoting $fm will make echoing it with newlines
echo "$fm" | xclip -selection clipboard

