#!/usr/bin/env bash

interface=$(ip link | grep wlp | cut -d " " -f 2)
interface=${interface::-1}
echo "Restarting for interface: $interface"

systemctl restart wpa_supplicant@$interface
systemctl --no-pager status wpa_supplicant@$interface

exit_status=1
while [ $exit_status -ne 0 ]; do
	sleep 2
	ping google.com -c 1 2> /dev/null
	exit_status=$?
done
